Added dotnet7-sdk
ScoopInstaller/Versions pull request #1488
Opened 2023-12-08 17:35 UTC by thedjdoorn

Since .NET 8 is the current version as of November 14th, version 7 should be included in the versions bucket. This might also be a fix for Scoop-managed applications that still use older .NET versions (i.e. `extras/fancontrol`, which also has a .Net 8 version, but the maintainer didn't bother). It would also be a good idea to consider adding a .NET 7 version of `extras/windowsdesktop-runtime` so users don't need the entire SDK, but that's for a different issue.

This manifest has been copied from the last .NET 7 release on main, with a small version bump to 7.0.404

Closes #1483

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-12-19 15:36 UTC, val1984 commented
/verify

2023-12-19 15:50 UTC, val1984 requested changes
Thank you for your PR. As written in the [contributing guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md), it should pass the `/verify` check before being considered for human review by someone who has push rights on the repo (unfortunately not me 🙂).

2023-12-19 15:50 UTC, val1984 commented on bucket/dotnet7-sdk.json
> +        "jsonpath": "$..releases-index[?(@.support-phase == 'active')].latest-sdk",
Changing this line to this should make checkver pass:
```json
"jsonpath": "$..releases-index[?(@.channel-version == '7.0')].latest-sdk",
```

2023-12-20 13:29 UTC, val1984 commented
/verify

2023-12-22 07:54 UTC, val1984 approved these changes
Everything looks good, now awaiting a review by someone with push privileges 🙂

2024-01-24 10:01 UTC, lsymds commented
Any chance of getting this reviewed @HUMORCE ? Thanks!

2024-01-24 16:30 UTC, HUMORCE approved these changes

2024-01-24 16:55 UTC, merged

2024-01-25 21:41 UTC, lsymds commented
Thanks @HUMORCE - appreciate it.