Odin@2024-12: Fix installation failing
ScoopInstaller/Versions pull request #2083
Opened 2024-12-30 13:01 UTC by anshul-bharat

# Odin installation fails

```console
PS D:\git\Versions> scoop install odin
Installing 'odin' (2024-12) [64bit] from 'versions' bucket
Loading odin-windows-amd64-dev-2024-12.zip from cache
Checking hash of odin-windows-amd64-dev-2024-12.zip ... ok.
Extracting odin-windows-amd64-dev-2024-12.zip ... done.
Linking D:\Programs\scoop\apps\odin\current => D:\Programs\scoop\apps\odin\2024-12
Creating shim for 'odin'.
Get-Command : The term 'odin.exe' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At D:\Programs\scoop\apps\scoop\current\lib\install.ps1:757 char:21
+             $bin = (Get-Command $target).Source
+                     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (odin.exe:String) [Get-Command
   ], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.
   Commands.GetCommandCommand

Can't shim 'odin.exe': File doesn't exist.
```

I updated `bin` path in manifest to include extra `dist` directory, since it was not matching with the directory structure inside package zip. which causes above error.

Same issue was occuring for `odin-dev 2024-12` and `odin-nightly 2024-12` updated them as well!

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-12-30 13:02 UTC, anshul-bharat commented
/verify updated manifest to fix odin installation.

2024-12-30 13:03 UTC, anshul-bharat commented
/verify updated manifest to fix odin installation.

2025-01-03 16:35 UTC, brian6932 requested changes
`./dist/` is the only directory, it should be the `extract_dir`, not added to the bin path.

2025-01-03 16:35 UTC, brian6932 commented on bucket/odin-nightly.json
>      "extract_dir": "windows_artifacts",
```suggestion
    "extract_dir": "dist",
    "bin": "odin.exe",
```

2025-01-03 16:35 UTC, brian6932 commented on bucket/odin-dev.json
> +    "bin": "dist/odin.exe",
```suggestion
    "extract_dir": "dist",
    "bin": "odin.exe",
```

2025-01-03 16:35 UTC, brian6932 commented on bucket/odin.json
> +    "bin": "dist/odin.exe",
```suggestion
    "extract_dir": "dist",
    "bin": "odin.exe",
```

2025-01-03 16:37 UTC, brian6932 commented
fixes #1778
fixes #1805

2025-04-24 07:51 UTC, closed without merging