tomcat9: Add version 9.0.45
ScoopInstaller/Versions pull request #280
Opened 2021-04-08 00:56 UTC by davidxuang

* Related: lukesampson/scoop-extras#5990

2021-04-12 07:27 UTC, davidxuang commented on bucket/tomcat7.json
> +    },
```suggestion
    },
```

2021-04-12 07:27 UTC, davidxuang commented on bucket/tomcat8.json
> +    },
```suggestion
    },
```

2021-04-12 07:27 UTC, davidxuang commented on bucket/tomcat9.json
> +    },
```suggestion
    },
```

2021-05-11 09:27 UTC, janicmikes requested changes
I adjusted the url of tomcat-9 to match the redirects from apache.

You may want to adjust them for the 6,7 and 8 versions as well.

2021-05-11 09:27 UTC, janicmikes commented on bucket/tomcat9.json
> +        "url": "https://www.apache.org/dist/tomcat/tomcat-9/?C=M;O=D",
```suggestion
        "url": "https://downloads.apache.org/tomcat/tomcat-9/?C=M;O=D",
```

2021-05-11 09:27 UTC, janicmikes commented on bucket/tomcat9.json
> +                "url": "https://www.apache.org/dist/tomcat/tomcat-$majorVersion/v$version/bin/apache-tomcat-$version-windows-x64.zip"
```suggestion
                "url": "https://downloads.apache.org/tomcat/tomcat-$majorVersion/v$version/bin/apache-tomcat-$version-windows-x64.zip"
```

2021-05-11 09:27 UTC, janicmikes commented on bucket/tomcat9.json
> +                "url": "https://www.apache.org/dist/tomcat/tomcat-$majorVersion/v$version/bin/apache-tomcat-$version-windows-x86.zip"
```suggestion
                "url": "https://downloads.apache.org/tomcat/tomcat-$majorVersion/v$version/bin/apache-tomcat-$version-windows-x86.zip"
```

2021-10-29 18:57 UTC, HUMORCE commented
@davidxuang hey, please update `tomcat8.json` and `tomcat9.json` to latest version.

2021-10-30 06:23 UTC, HUMORCE submitted a review, later dismissed

2021-10-30 06:29 UTC, HUMORCE approved these changes

2021-10-30 06:30 UTC, HUMORCE commented
/verify

2021-10-30 06:31 UTC, merged

2021-10-30 06:40 UTC, HUMORCE commented
sorry, i made a mistake here. 🤐