Jetbrains apps: Add RC and EAP packages
ScoopInstaller/Versions pull request #379
Opened 2022-01-04 09:16 UTC by issaclin32

This adds RC (release condidate) and EAP (early access program) of **JetBrains** apps to the bucket.

Notes:
* I have (1) run autoupdate, (2) installed, and (3) run the software of all these packages, to make sure they work properly.

2022-01-04 15:11 UTC, rashil2000 requested changes

2022-01-04 15:12 UTC, rashil2000 requested changes

2022-01-04 15:12 UTC, rashil2000 commented on bucket/webstorm-eap.json
> +        "url": "https://download.jetbrains.com/webstorm/WebStorm-$preReleaseVersion.exe#/cosi.7z",
```suggestion
        "url": "https://download.jetbrains.com/webstorm/WebStorm-$preReleaseVersion.exe#/dl.7z",
```

2022-01-04 16:18 UTC, rashil2000 requested changes
One last thing: on the rare chance that someone doesn't have Extras bucket installed, the installation of all IDEs will fail. We should copy the `portable.ps1` script to Versions bucket too, and reference that instead of the one in Extras.

2022-01-04 16:18 UTC, rashil2000 commented on bucket/rider-eap.json
> +        ]
```suggestion
        "script": "& \"$bucketsdir\\extras\\scripts\\jetbrains\\portable.ps1\" $dir $persist_dir"
```

2022-01-05 02:33 UTC, issaclin32 commented
> One last thing: on the rare chance that someone doesn't have Extras bucket installed, the installation of all IDEs will fail. We should copy the `portable.ps1` script to Versions bucket too, and reference that instead of the one in Extras.

Done. Thank you so much for taking your time to check this.

2022-01-05 05:37 UTC, rashil2000 approved these changes

2022-01-05 05:39 UTC, merged