Pijul: Add version 1.0.0-beta
ScoopInstaller/Versions pull request #404
Opened 2022-01-26 16:38 UTC by nightscape

Pijul is a free and open source (GPL2) distributed version control system. Its distinctive feature is to be based on a theory of patches, while still being fast and scalable. This makes it easy to learn and use, without any compromise on power or features.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-26 16:45 UTC, rashil2000 requested changes
You need to use architecture 64bit block

2022-01-26 16:45 UTC, rashil2000 commented on bucket/pijul.json
> +    "description": "Pijul is a free and open source (GPL2) distributed version control system. Its distinctive feature is to be based on a theory of patches, while still being fast and scalable. This
```suggestion
    "description": "A fast and scalable distributed version control system, based on a theory of patches.",
```

2022-02-03 12:19 UTC, tech189 commented
Here's the 64bit architecture block added to `url`, `hash` and `autoupdate`:
```json
{
    "version": "1.0.0-beta",
    "description": "A fast and scalable distributed version control system, based on a theory of patches.",
    "homepage": "https://pijul.org",
    "license": "GPL-2.0-only",
    "architecture": {
        "64bit": {
            "url": "https://github.com/boringcactus/pijul-windows-builds/releases/download/1.0.0-beta/pijul.exe",
            "hash": "99192ae7b358c2a6c1a6b92a1da09bff5d8d0f85db8cb4aa050e83f922b6112d"
        }
    },
    "bin": "pijul.exe",
    "checkver": {
        "github": "https://github.com/boringcactus/pijul-windows-builds/",
        "re": "(?<version>[\\d\\w.-]+)/pijul\\.exe"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/boringcactus/pijul-windows-builds/releases/download/$version/pijul.exe"
            }
        }
    }
}
```

2022-02-03 20:38 UTC, nightscape commented
Sorry, my family and me caught covid. I'll update the PR once I'm back on track.

2022-02-03 20:51 UTC, rashil2000 commented
/verify

2022-02-03 20:54 UTC, merged

2022-02-03 20:54 UTC, rashil2000 commented
No worries @nightscape, I made the changes.

Please take care.

2022-02-03 22:59 UTC, nightscape commented
Thank you @rashil2000 ❤️