espanso-alpha: Add version v2.1.3-alpha
ScoopInstaller/Versions pull request #422
Opened 2022-02-16 00:10 UTC by hmnd

Adds alpha version of [espanso](https://espanso.org/)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-02-16 05:21 UTC, rashil2000 commented
Use the portable version

2022-02-16 05:24 UTC, rashil2000 commented on bucket/espanso-alpha.json
> +            "start",
```suggestion
            "launcher",
```

Shouldn't this be "launcher" instead?

2022-02-16 08:29 UTC, rashil2000 commented
> Use the portable version

2022-02-16 15:02 UTC, tech189 requested changes
Take a look at my suggestions - they change it from an installer to portable, fix autoupdate and add the icon which is missing from portable version :)

2022-03-19 14:00 UTC, rashil2000 commented
@tech189 can you open a new superseding PR with your suggestions?

2022-03-22 13:49 UTC, closed without merging