(chore): Migrate CI to GitHub Actions
ScoopInstaller/Versions pull request #441
Opened 2022-03-09 07:54 UTC by rashil2000

Relates to https://github.com/ScoopInstaller/Main/pull/3361

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-03-09 07:55 UTC, rashil2000 commented
Pinging @r15ch13 to disable the AppVeyor pipeline

2022-03-09 16:29 UTC, niheaven requested changes

2022-03-09 16:29 UTC, niheaven commented on .github/workflows/ci.yml
> +          $env:SCOOP_HOME="$(Resolve-Path '.\scoop_core')"
```suggestion
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
```

2022-03-09 16:29 UTC, niheaven commented on .github/workflows/ci.yml
> +          $env:SCOOP_HOME="$(Resolve-Path '.\scoop_core')"
```suggestion
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
```

2022-03-09 16:29 UTC, niheaven commented on bin/test.ps1
>  if(!$env:SCOOP_HOME) { $env:SCOOP_HOME = Resolve-Path (scoop prefix scoop) }
```suggestion
if (!$env:SCOOP_HOME) { $env:SCOOP_HOME = Convert-Path (scoop prefix scoop) }
```

2022-03-09 16:29 UTC, niheaven commented on bin/test.ps1
> +$result = Invoke-Pester "$psscriptroot/.." -PassThru
```suggestion
$result = Invoke-Pester "$PSScriptRoot\.." -PassThru
```

2022-03-09 16:45 UTC, niheaven approved these changes

2022-03-09 16:46 UTC, merged

2022-11-21 23:09 UTC, Jimimaku commented
> Relates to [ScoopInstaller/Main#3361](https://github.com/ScoopInstaller/Main/pull/3361)
> 
> * [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-11-21 23:35 UTC, Jimimaku commented
> Relates to [ScoopInstaller/Main#3361](https://github.com/ScoopInstaller/Main/pull/3361)
> 
> * [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).